added & revised feedback system in both view and model
OlinSTEP/STEPNavigationApp pull request #39
Opened 2023-06-20 18:30 UTC by Mguoji

- I changed the arrived view file so that
1. thumbs up and thumbs down buttons will show on the arrived view 
2. clicking thumbs down will navigate to another interface that allows the user to specify the problem

- I added a feedback survey data model file to 
1. allow the feedback data to be stored in a json file format
2. upload to the firebase with a route ID attached

- Paul added "func uploadFeedback" to the firebase manager model file to upload the survey data into firebase storage

2023-06-20 20:21 UTC, EvesK commented
Hi Muya!
Great job on this! I have a few UX/UI comments and then I found a bug that should definitely be addressed before this gets pulled into main. 

To start, the bug is that when you are putting in feedback (after clicking thumbs down), you are able to open multiple text fields but when you type the text is the same in every field (see attached picture (don't worry that the colors are weird, my color scheme is set to blue-yellow at the moment). Since I can imagine someone having multiple issues with the route, I think the user should be able to put different answers in each text field and submit text for multiple fields if needed. 

As far as UI/UX, I have a few comments.
- I think overall we should definitely just have a meeting and make sure to unify the color and styling with the rest of the app, especially given that the multiple color scheme options
- I can tell that on the thumbs down screen, you have the four buttons for issues and then if you click one of them it opens a text field to tell you more about the issue. But, I think this user flow could be way more obvious. To start, it is unclear from the styling that the four options are necessarily buttons. A great way to start with fixing this is to give them the same styling (pill shaped appearance for small buttons or large rounded rectangle for lists) as the rest of the buttons on the app. Additionally, I don't feel that the light yellow color properly conveys that they are unselected buttons. In other parts of the app, I use an outlined button with no fill to indicate an unselected button, and then fill in the button (and invert the color of the text) when it is clicked to indicate it is filled. If you want to see this in action you can pull the latest from the views branch and go look at the crumb color settings, for example. Maybe we could employ something similar here?
- Also on this page, I think some of the buttons could have better labels. First off, I think the label for the last button should be "other" (singular) instead of "others", since it is a response to the question "What was the issue?". Second, I think the third button could have a more descriptive title; I'm not entirely sure what you are getting at with the current one. Is it asking a) could not resolve/find anchor? or b) anchor was in wrong place ? I think these are two very different issues, so it would be important to clarify which one you are asking about (or maybe ask about both in separate buttons?)
- When you select a button it opens the optional text field. It is unclear from the current styling that the text field is optional. Maybe you could add a text label above the field that says something like "Optional: Please describe the issue."
- I think the done button could have a more descriptive label, like "send feedback" or something that indicates that by clicking it they are actually giving us feedback
- Lastly, when you click the thumbs up and the done buttons I think instead of taking you back to home it should get rid of the feedback popup (the text and the two buttons) and replace it with text that says "Feedback sent" or something like that and then allow the user to continue on and press the home button that is already on the page. The issue with sending the user directly to the home page is that generally you don't want a button to do two things to the user, especially when it comes to screen readers since this can confuse the reader because the buttons action doesn't align with the label/icon on the button. 

One thing you may have noticed about me by now is that I give a lot of feedback. This is because I am super excited about what you've created so far and want to give you lots of ideas moving forward. But they are just that, ideas, so please feel free to take what you want and leave the rest. I am super happy to talk more about any of these, and if you decide to implement some of the ideas around styling it to match the rest of the app please let me know because I can show you where to find examples of how I style the buttons and all of that in the code. 
Thanks,
Evelyn

2023-06-22 06:37 UTC, paulruvolo requested changes
Hi Muya.  This looks solid!  I made a few comments for you to fix.  Once you do I can approve the pull request.

2023-06-22 06:37 UTC, paulruvolo commented on STEP Navigation/Models/FeedbackDataModel.swift
> +            "The route led me into a large obstacle": isObstacleSelected,
I'm a little worried about this option as I don't want to convey that our system will help with obstacle avoidance.  I think it's okay for the time being, but it's something to keep in mind going forward.

2023-06-22 06:37 UTC, paulruvolo commented on STEP Navigation/Models/FeedbackDataModel.swift
> +
It would be great to add some documentation to this file.  Can you look at the examples in the other model classes and replicate that here?  Make sure to learn about keyboard shortcuts in XCode for inserting documentation stubs (I think it's option-command-slash while having the cursor over a particular entity you want to document).

2023-06-22 06:37 UTC, paulruvolo commented on STEP Navigation/Models/FirebaseManager.swift
> +    func uploadFeedback(_ data: Data) {
add documentation here as well (I know I wrote it, but it's good practice!)

2023-06-22 06:37 UTC, paulruvolo commented on STEP Navigation/Models/FirebaseManager.swift
> +    private func observeQuery(query: Query) {
This function is a holdover from something I did that is no longer needed.  Can you delete it?

2023-06-22 06:37 UTC, paulruvolo commented on STEP Navigation/Models/LocationDataModel.swift
> +//    /// Represents a generic indoor destination.  This is a placeholder value for when the specific category has not yet been set.
Can we delete this commented out code?  I know it's not something you did, but since you created the pull request, that would be great.

2023-06-22 06:37 UTC, paulruvolo commented on STEP Navigation/STEP_NavigationApp.swift
> +//@main
You can delete the commented out code.  We can always look in our the version history if we need to see it.

2023-06-22 06:37 UTC, paulruvolo commented on STEP Navigation/Views/MultiplechoiceView.swift
> +//  ThumbsDownMultiplechoice.swift
What is going on with this view?  Is this obsolete?  If the file is no longer needed, make sure to delete it so it doesn't go into the main branch.

2023-06-22 06:37 UTC, paulruvolo commented on STEP Navigation/Views/NavigatingView.swift
> +//            if showingConfirmation {
Delete this commented out code.

2023-06-28 20:18 UTC, merged