Refactor of views files
OlinSTEP/STEPNavigationApp pull request #41
Opened 2023-07-01 01:26 UTC by EvesK

Refactored all views files with new components. Renamed files for clarity. Removed tri-color color scheme option.
New Components (which have been implemented throughout the views files):
Buttons
- Large Navigation Link
- Small Navigation Link
- Large Button
- Small Button
Menus and Text Fields
- Segmented Toggle
- Custom Text Field
- Combo Box
- Picker Button and Picker Page (used in concert)
Header
- Header Button
- Screen Header
Overlays and Popups
- AR View Text Overlay
- Confirmation Popup
- Loading Popup
- Anchor Info Popup
Miscellaneous
- Anchor Details Text
- Checklist Item
- Screen Background (a component that, when wrapped around a view, applies the appropriate global background color to the view)
- Nearby Distance Threshold
- List of Anchors
- Left Label
- Ordered List

2023-07-03 17:41 UTC, paulruvolo requested changes
Looks great!  After making a couple minor changes, please merge.

2023-07-03 17:41 UTC, paulruvolo commented on STEP Navigation/Views/Assets/Colors.swift
>          settingsManager.loadColorScheme().0
I wonder a bit whether we should make the color scheme behave similarly to the other settings (even though it's not a settings managed through the settings app).  We could make the scheme a proper var and use @Published to make views dynamically respond to changes.  This doesn't have to be fixed to merge the request, but I wanted to mark it here.

2023-07-03 17:41 UTC, paulruvolo commented on STEP Navigation/Views/Assets/Components.swift
This file is still part of the pull request but is no longer part of the XCode project.  I think it can be removed from the repo using `git rm` from the terminal.

2023-07-03 17:41 UTC, paulruvolo commented on STEP Navigation/Views/Assets/Popups.swift
I think this is another file that is obsolete (no longer part of the XCode project).  See my earlier comment about `git rm`ing it.

2023-07-03 17:41 UTC, paulruvolo commented on STEP Navigation/Views/HomeView.swift
> +    let minimumGeoLocationAccuracy: GeoLocationAccuracy = .coarse //TODO: investigate: if I set this to anything other than coarse it doesn't work
The issue is that we typically turn off the fancy ARCore geo positioning when we are the home screen.  This means we only have the GPS-only positioning running (.coarse).

2023-07-03 17:41 UTC, paulruvolo commented on STEP Navigation/Views/HomeView.swift
> +                        ScreenHeader(title: "Clew Maps 2", subtitle: "Precise Short Distance Navigation for the Blind and Visually Impaired", backButtonHidden: true)
We need a better name!!!  Maybe co-designers can name it?

2023-07-03 17:41 UTC, paulruvolo commented on STEP Navigation/Views/SettingsView.swift
> +                        VStack(spacing: 14) {
Remove commented out code

2023-07-03 17:41 UTC, paulruvolo commented on STEP Navigation/Views/StartAnchorListView.swift
> +//    @State var chosenStart: LocationDataModel?
Is this still needed?

2023-07-05 05:26 UTC, EvesK commented on STEP Navigation/Views/Assets/Colors.swift
>          settingsManager.loadColorScheme().0
This is a great idea. For now I have a screen that prompts you to restart the app, but I've been hoping to find a way to make it dynamic without having to do that. I will add it to the to-do list for the next merge

2023-07-05 05:29 UTC, EvesK commented on STEP Navigation/Views/HomeView.swift
> +    let minimumGeoLocationAccuracy: GeoLocationAccuracy = .coarse //TODO: investigate: if I set this to anything other than coarse it doesn't work
Got it. I just wanted to double check since it seemed a bit odd.

2023-07-05 05:30 UTC, EvesK commented on STEP Navigation/Views/SettingsView.swift
> +                        VStack(spacing: 14) {
How do you always manage to find more code that I forgot to remove? Thanks!

2023-07-05 05:32 UTC, EvesK commented on STEP Navigation/Views/HomeView.swift
> +                        ScreenHeader(title: "Clew Maps 2", subtitle: "Precise Short Distance Navigation for the Blind and Visually Impaired", backButtonHidden: true)
We really do

2023-07-05 05:39 UTC, merged