Bug Fixes and Getting Ready for Co-Designer Phase 1
OlinSTEP/STEPNavigationApp pull request #46
Opened 2023-07-08 05:27 UTC by EvesK

Implemented bug fixes including styling and voiceover accessibility changes. Additionally;
- modified navigate flow so that anchor details only display after choosing destination and start anchor
- modified tutorials using new bullet point text
- added video player into tutorial

2023-07-08 05:32 UTC, EvesK commented
@paulruvolo ; a few things here. I went ahead with the pull request but there are still two major bugs. The first is that I don't think the VideoView ever got fully checked in properly. Can you make sure that it does and that the code runs with the VideoView code? I previously had it commented out so that I could test other things but uncommented it right before pushing. Second, there is a bug when creating an anchor where sometimes it tries to force unwrap a nil value. This occurs after the "Trying to Host Anchor" announcement. When this occurs, the screen freezes and I get the error message in the image below. The anchor still gets created but you have to restart the app and then it shows up as New Anchor in the manage view. Lastly, not a bug but I was attempting to implement a switch anchors button the anchor detail view that, if the user selected the start and end anchors in reverse by accident, would allow them to switch the two before navigating without having to go back and reselect everything. I wasn't able to get it working, but I left my code commented out in the file (Anchor Detail View). Totally optional, but if you could take a look and see if you have any ideas for how to get that working that would be awesome. Thanks!

<img width="1439" alt="Screenshot 2023-07-07 at 8 04 31 PM" src="https://github.com/OlinSTEP/STEPNavigationApp/assets/88510334/5f894389-bfbb-4414-91ce-2ea6b3f8d10e">

2023-07-09 03:59 UTC, paulruvolo requested changes
Looks great.  I do have some thoughts that the tutorial could be improved quite a bit.  I hope we have time to fix that on Monday.  Maybe we need a separate pull request to do the tutorial fixes.

2023-07-09 03:59 UTC, paulruvolo commented on STEP Navigation/Views/StartupViews.swift
> +                VideoView(videoID: "G5BonVtsfmY")
This is file is not showing up when I open the project in XCode. VideoView.swift needs to be added to the project by dragging it into the Views folder in XCode.  The file is already there, it just isn't linked into pbxproj file.

2023-07-09 03:59 UTC, paulruvolo commented on STEP Navigation/Views/StartupViews.swift
> +                ScrollView {
We refer to the app as Clew and Clew Maps 2 in different places.  Maybe we can unify it?  Can we give it a working title?

2023-07-09 03:59 UTC, paulruvolo commented on STEP Navigation/Views/StartupViews.swift
> +                        StartupText("Clew Maps 2 will log the 3D path that your phone travels when using the app. We use this 3D path information to understand the app's shortcomings and to improve i
This is now inaccurate.  We are tying the 3D path information to the GPS position.

2023-07-09 03:59 UTC, paulruvolo commented on STEP Navigation/Views/SettingsDetailViews.swift
> +        }
fix indent.

2023-07-09 03:59 UTC, paulruvolo commented on STEP Navigation/Views/AnchorDetailEditView.swift
> +//                                if newCategory == "Exit" {
Are we also removing bus stops / external doors as options?

2023-07-09 03:59 UTC, paulruvolo commented on STEP Navigation/Views/StartupViews.swift
> +                    UnorderedList(listItems: ["Clew will vibrate and give you audio clues as you follow a route. If you veer off the path the clues will stop.", "If you stop hearing the audio clues,
Let's make this more specific.  Add information on how the audio cues (let's also use that instead of "clues") correspond with whether the user is on track or not.

2023-07-09 04:15 UTC, paulruvolo commented
I put a solution for the VideoView.swift issue.  I think I fixed this in main, but it is not in your branch.  In any case, you can use the solution in the review.

2023-07-09 21:37 UTC, EvesK commented on STEP Navigation/Views/StartupViews.swift
> +                ScrollView {
I implemented Clew Maps 2 as the working name everywhere I could find. I think I got everything.

2023-07-09 21:38 UTC, EvesK commented on STEP Navigation/Views/StartupViews.swift
> +                        StartupText("Clew Maps 2 will log the 3D path that your phone travels when using the app. We use this 3D path information to understand the app's shortcomings and to improve i
Got it.

2023-07-09 21:42 UTC, EvesK commented on STEP Navigation/Views/AnchorDetailEditView.swift
> +//                                if newCategory == "Exit" {
Yes. What do you think is the best way to do that? I imagine if we just comment those types out it is going to cause all kinds of bugs. I'm thinking maybe a filter at manage anchor list view and destinations type list view? And also on the anchor detail view so that you can't select that type.

2023-07-09 21:43 UTC, EvesK commented on STEP Navigation/Views/StartupViews.swift
> +                    UnorderedList(listItems: ["Clew will vibrate and give you audio clues as you follow a route. If you veer off the path the clues will stop.", "If you stop hearing the audio clues,
Could you pass this feedback along to Lisan and Nina? They seem to be doing most of the tutorial writing.

2023-07-09 22:21 UTC, EvesK commented on STEP Navigation/Views/AnchorDetailEditView.swift
> +//                                if newCategory == "Exit" {
I went ahead and implemented this with the three filters I suggested above. If you want to do it a different way please let me know!

2023-07-10 20:20 UTC, merged